exc_tb  # unused variable (readmetester/src/__init__.py:198)
exc_type  # unused variable (readmetester/src/__init__.py:198)
exc_val  # unused variable (readmetester/src/__init__.py:198)
fixture_main  # unused function (tests/conftest.py:30)
fixture_make_readme  # unused function (tests/conftest.py:47)
fixture_nocolorcapsys  # unused function (tests/conftest.py:65)
fixture_patch_argv  # unused function (tests/conftest.py:15)
